---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: cryptocom/chain-test:v0.5
  pull: if-not-exists
  commands:
  - export CARGO_HOME=$PWD/drone/cargo
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - ./integration-tests/build.sh

- name: integration-tests
  image: cryptocom/chain-test:v0.5
  pull: if-not-exists
  privileged: true
  volumes:
  - name: sgx
    path: /dev/sgx
  environment:
    SPID:
      from_secret: SPID
    IAS_API_KEY:
      from_secret: IAS_API_KEY
  commands:
  - export CARGO_TARGET_DIR=$PWD/drone/target
  - export PYTHON_VENV_DIR=$PWD/drone/venv
  - LD_LIBRARY_PATH=/opt/intel/sgx-aesm-service/aesm /opt/intel/sgx-aesm-service/aesm/aesm_service
  - ./integration-tests/run.sh

- name: teardown
  image: cryptocom/chain-test:v0.5
  pull: if-not-exists
  commands:
  - ./integration-tests/cleanup.sh
  when:
    status:
      - success
      - failure

volumes:
  - name: sgx
    host:
      path: /dev/sgx

trigger:
  branch:
  - master
  - staging
  - trying
  event:
  - push

---
kind: signature
hmac: ea35175237135c70994b826c97ddaeee9f5f4c329eda107cbc9140dd9c0002ad

...
